# Generated by Django 4.2.9 on 2024-01-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlugarCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('foto', models.ImageField(upload_to='home')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ano_fabricacao', models.IntegerField()),
                ('valor', models.FloatField()),
                ('avaliacao', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
