# Generated by Django 5.0.1 on 2024-01-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano_publicacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='quantidade_paginas',
            field=models.IntegerField(),
        ),
    ]
