# Generated by Django 4.2.9 on 2024-01-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtracaoTuristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='atracoes_turisticas')),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cad_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
